import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'ANTRO',
    short_name: 'ANTRO',
    description:
      'Discover unique, high-quality streetwear designed for the modern individual.',
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#ffffff',
    icons: [
      {
        // Generated by app/icon.tsx
        src: '/icon',
        sizes: '32x32',
        type: 'image/png',
      },
      {
        // Generated by app/apple-icon.tsx
        src: '/apple-icon',
        sizes: '180x180',
        type: 'image/png',
      },
    ],
  }
}
