-- Orders table — the single table backing the checkout flow.
--
-- Reconstructed 2026-08-14 from types/supabase.ts and lib/orders.ts after the
-- Supabase project came back empty and took the original (unversioned) schema
-- with it. Keep this file authoritative from here on: change the schema by
-- adding a migration, never by editing the database by hand.

create table if not exists public.orders (
  -- Generated by the application (uuidv4 in lib/orders.ts), not by Postgres:
  -- the insert always supplies it, so there is deliberately no default here.
  id                       uuid primary key,

  order_number             text not null unique,
  status                   text not null default 'pending',

  customer_name            text not null,
  customer_email           text not null,
  customer_phone           text,

  address_line1            text not null,
  address_line2            text,
  address_city             text not null,
  -- Not every country has a state/province; the webhook writes '' rather than
  -- NULL when Stripe gives us nothing, so this stays NOT NULL.
  address_state            text not null,
  address_postal           text not null,
  address_country          text not null,

  -- Cart line items, copied out of the PaymentIntent metadata.
  items                    jsonb not null default '[]'::jsonb,

  subtotal                 numeric(10, 2) not null,
  shipping                 numeric(10, 2) not null,
  total                    numeric(10, 2) not null,

  -- UNIQUE is what makes webhook delivery idempotent: a duplicate
  -- payment_intent.succeeded loses the race on insert and is treated as
  -- success rather than creating a second order.
  stripe_payment_intent_id text unique,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

-- The webhook looks orders up by payment intent on every delivery.
create index if not exists orders_stripe_payment_intent_id_idx
  on public.orders (stripe_payment_intent_id);

-- Orders are only ever touched by the server using the service role key, which
-- bypasses RLS. Enabling RLS with no permissive policy therefore denies the
-- anon and authenticated roles outright — nothing reaches this table from the
-- browser, even though the Supabase URL and anon key are public.
alter table public.orders enable row level security;

drop policy if exists "Deny all access to anon and authenticated" on public.orders;
create policy "Deny all access to anon and authenticated"
  on public.orders
  for all
  to anon, authenticated
  using (false)
  with check (false);
